[project]
name = "kairos"
version = "0.2.2"
description = "Kairós — Tempo de qualidade com Deus. App cristão multiplataforma com hinários, bíblia, meditação diária e agente litúrgico"

[tool.flet]
desktop_flavor = "light"

[tool.flet.app]
assets_dir = "assets"
icon = "icon.ico"

[tool.flet.android]
permissions = [
    "android.permission.INTERNET",
    "android.permission.REQUEST_INSTALL_PACKAGES",
    "android.permission.READ_EXTERNAL_STORAGE",
    "android.permission.WRITE_EXTERNAL_STORAGE",
]

[tool.flet.android.deep_linking]
scheme = "nhaapp"
host = "login-callback"

[tool.pyright]
extraPaths = ["."]
venvPath = "."
venv = ".venv"


